version: '3.8'
services:
  ###########################
  # APPLICATION SERVICES
  ###########################
  app:
    build: .
    restart: always
    healthcheck:
      start_period: 60ms
      timeout: 120s
      interval: 30s
      test: ifconfig | grep broadcast
    ports:
      - 3000:3000
    env_file: .env
    depends_on:
      - database
    volumes:
      - ./:/usr/share/app
      - /usr/share/app/node_modules
    networks:
      - node_networks
  ###########################
  # POSTGRES SERVICES
  ###########################
  database:
    image: postgres:14-alpine
    restart: always
    healthcheck:
      start_period: 60ms
      timeout: 120s
      interval: 30s
      test: ifconfig | grep broadcast
    ports:
      - 5432:5432
    env_file: .env
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - database-data:/var/lib/postgres/data
    networks:
      - node_networks
  ###########################
  # VOLUME PERSISTENT DATA
  ###########################
volumes:
  database-data:
  ###########################
  # NETWORK SHARING GROUP
  ###########################
networks:
  node_networks: